---
name: Update website

on:
  push:
    branches:
      - main
      - head-docs

jobs:
  build-website:
    name: Generate website
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: downward-markup
          fetch-depth: 0 # fetch all history for all branches
          ref: main
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python3 -m pip install -r downward-markup/scripts/requirements.txt

      - name: Build the website
        run: |
          # obtain all branches from repository
          cd downward-markup/
          git fetch --all; for remote in `git branch -r | grep -v \> | grep -v main`; do git branch --track ${remote#origin/} $remote; done
          git branch

          # call the build script
          cd scripts
          ./build_website.py

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: websitezip
          path: downward-markup/scripts/site/site.zip

  deploy-website:
    name: Deploy website
    needs: build-website
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: aibasel/downward-website
          token: ${{ secrets.AIBASEL_DOWNWARD_WEBSITE_PAT }}
          path: downward-website
          ref: gh-pages

      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: websitezip

      - name: Sync the website
        run: |
          cd downward-website
          rm -rf *
          cd ..
          unzip -u site.zip -d gh-pages/
          ls -la downward-website
          cd downward-website
          git restore CNAME
          git add -A
          git status
          git commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> -m "update website"
          git push
